name: Deno

on:
  push:
    branches: [master]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: "54.88.121.207"
        username: "ubuntu"
        key: ${{ secrets.EC2KEY }}
        port: 22
        script: |

          cd liberato-software
          sudo git pull
          pm2 restart liberato-software
          sudo systemctl restart nginx
          echo 'OK'